# Generated by Django 3.2.8 on 2021-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и Фамилия')),
                ('date', models.DateTimeField(verbose_name='Дата рождения')),
                ('cost', models.CharField(max_length=100, verbose_name='Цена')),
            ],
        ),
    ]
